/*
** EPITECH PROJECT, 2021
** SYSCALLS_H
** File description:
** syscall_list
*/


#ifndef SYSCALLS_H
#define SYSCALLS_H

#include "ftrace.h"

static const syscall_t SCALL_LIST[] =
{
    {"read", "usu"}, {"write", "usu"}, {"open", "sdd"},
    {"close", "u"}, {"stat", "st"}, {"fstat", "ut"},
    {"lstat", "st"}, {"poll", "tud"}, {"lseek", "uuu"},
    {"mmap", "uuuuuuu"}, {"mprotect", "uuu"}, {"munmap", "uu"},
    {"brk", "u"}, {"rt_sigaction", "dttu"}, {"rt_sigprocmask", "dttu"},
    {"rt_sigreturn", "u"}, {"ioctl", "uuu"}, {"pread64", "usuu"},
    {"pwrite64", "utu"}, {"readv", "utu"}, {"writev", "utu"},
    {"access", "sd"}, {"pipe", "d"}, {"select", "dp"},
    {"sched_yield", 0x0}, {"mremap", "uuuuu"}, {"msync", "uud"},
    {"mincore", "uus"}, {"madvise", "uud"}, {"shmget",  "uud"},
    {"shmat", "dsd"}, {"shmctl", "ddt"}, {"dup", "u"},
    {"dup2", "uu"}, {"pause", 0x0}, {"nanosleep", "tt"},
    {"getitimer", "dt"}, {"alarm", "d"}, {"setitimer", "dtt"},
    {"getpid", 0x0}, {"sendfile", "dd"}, {"socket", "ddd"},
    {"connect", "dtd"}, {"accept", "dtd"}, {"sendto", "dpuutd"},
    {"recvfrom", "dpuutd"}, {"sendmsg", "dtu"}, {"recvmsg", "dtu"},
    {"shutdown",0x0}, {"bind","dtd"}, {"listen","dd"},
    {"getsockname", "dtp"}, {"getpeername", "dtd"}, {"socketpair","dddp"},
    {"setsockopt","dddsd"}, {"getsockopt","ddds"}, {"clone", "uupp"},
    {"fork",0x0}, {"vfork", 0x0}, {"execve","saa"},
    {"exit","d"}, {"wait4", "updt"}, {"kill","ud"},
    {"uname", "t"}, {"semget","udd"}, {"semop", "dtu"},
    {"semctl","dddp"}, {"shmdt", "s"}, {"msgget","ud"},
    {"msgsnd","dtud"}, {"msgrcv","dtuld"}, {"msgctl","ddt"},
    {"fcntl", "uuu"}, {"flock", "uu"}, {"fsync", "u"},
    {"fdatasync", "u"}, {"truncate","sl"}, {"ftruncate", "ul"},
    {"getdents","utu"}, {"getcwd","su"}, {"chdir", "s"},
    {"fchdir","u"}, {"rename","ss"}, {"mkdir", "sd"},
    {"rmdir", "s"}, {"creat", "sd"}, {"link","ss"},
    {"unlink","s"}, {"symlink", "ss"}, {"readlink","ssd"},
    {"chown", "suu"}, {"fchown","uuu"}, {"lchown","suu"},
    {"umask", "d"}, {"gettimeofday","tt"}, {"getrlimit", "ut"},
    {"getrusage", "dt"}, {"sysinfo", "t"}, {"times", "t"},
    {"ptrace","ddlu"}, {"getuid",0x0},{"syslog","dsd"},
    {"getgid",0x0}, {"setuid","u"}, {"setgid","u"},
    {"geteuid", 0x0}, {"getegid", 0x0}, {"setpgid", "uu"},
    {"getppid", 0x0}, {"getpgrp", 0x0}, {"setsid",0x0},
    {"setreuid","uu"}, {"setregid", "uu"}, {"getgroups", "dp"},
    {"setgroups", "du"}, {"setresuid", "ppp"}, {"getresuid", "ppp"},
    {"setresgid", "uuu"}, {"getresgid", "ppp"}, {"getpgid", "u"},
    {"setfsuid", "u"}, {"setfsgid", "u"}, {"getsid", "u"},
    {"capget", "tt"}, {"capset", "tt"}, {"rt_sigpending", "uu"},
    {"rt_sigtimedwait", "pptu"}, {"rt_sigqueueinfo", "udp"},
    {"rt_sigsuspend", "pu"}, {"sigaltstack", "pp"}, {"utime", "st"},
    {"mknod", "suu"}, {"uselib", "u"}, {"personality", "u"}, {"ustat", "ut"},
    {"statfs", "st"}, {"fstatfs", "ut"}, {"sysfs", "duu"},
    {"getpriority", "dd"}, {"setpriority", "ddd"}, {"sched_setparam", "ut"},
    {"sched_getparam", "ut"}, {"sched_setscheduler", "ddt"},
    {"sched_getscheduler", "u"}, {"sched_get_priority_max", "d"},
    {"sched_get_priority_min", "d"}, {"sched_rr_get_interval", "ut"},
    {"mlock", "uu"}, {"munlock", "uu"}, {"mlockall","d"},
    {"munlockall",0x0}, {"vhangup", 0x0}, {"modify_ldt","dpu"},
    {"pivot_root","ss"}, {"_sysctl", "t"}, {"prctl", "duuuu"},
    {"arch_prctl","tdu"}, {"adjtimex","t"}, {"setrlimit", "ut"},
    {"chroot","s"}, {"sync",0x0}, {"acct","s"},
    {"settimeofday","tt"}, {"mount", "sssup"}, {"umount2", "sd"},
    {"swapon","sd"}, {"swapoff", "s"}, {"reboot","ddup"},
    {"sethostname", "sd"}, {"setdomainname", "sd"}, {"iopl","ut"},
    {"ioperm","uud"}, {"create_module", "uu"}, {"init_module", "pus"},
    {"delete_module", "su"}, {"get_kernel_syms", "t"},
    {"query_module","uuuuu"}, {"quotactl","usup"}, {"nfsservctl","uuu"},
    {"getpmsg", "uuuuu"}, {"putpmsg", "uuuuu"}, {"afs_syscall", "uuuuu"},
    {"tuxcall", "uuu"}, {"security","uuu"}, {"gettid",0x0},
    {"readahead", "duu"}, {"setxattr","sspud"}, {"lsetxattr", "sspud"},
    {"fsetxattr", "dspud"}, {"getxattr","sspd"}, {"lgetxattr", "sspu"},
    {"fgetxattr", "dspu"}, {"listxattr", "ssu"}, {"llistxattr","ssu"},
    {"flistxattr","dsu"}, {"removexattr", "ss"}, {"lremovexattr","ss"},
    {"fremovexattr","ds"}, {"tkill", "ud"}, {"time","p"}, {"futex", "pdutpu"},
    {"sched_setaffinity", "uup"}, {"sched_getaffinity", "uup"},
    {"set_thread_area", "u"}, {"io_setup","ut"}, {"io_destroy","u"},
    {"io_getevents","pllt"},  {"io_submit", "plt"}, {"io_cancel", "ptt"},
    {"get_thread_area", "u"},     {"lookup_dcookie","ull"},
    {"epoll_create","d"},   {"epoll_ctl_old", "uuuu"},
    {"epoll_wait_old","uuuu"},  {"remap_file_pages","uuuuu"},
    {"getdents64","utu"}, {"set_tid_address", "p"}, {"restart_syscall", 0x0},
    {"semtimedop","dtut"}, {"fadvise64", "duud"}, {"timer_create","utp"},
    {"timer_settime", "udtt"}, {"timer_gettime", "ut"},
    {"timer_getoverrun", "u"}, {"timer_delete", "u"},
    {"clock_settime", "ut"}, {"clock_gettime", "ut"}, {"clock_getres", "ut"},
    {"clock_nanosleep", "udtt"}, {"exit_group", "d"}, {"epoll_wait","dtdd"},
    {"epoll_ctl", "dddt"}, {"tgkill", "uud"}, {"utimes", "st"},
    {"vserver", "uuuuu"}, {"mbind", "uuupuu"}, {"set_mempolicy", "puu"},
    {"get_mempolicy", "ppuuu"}, {"mq_open", "sdut"}, {"mq_unlink", "s"},
    {"mq_timedsend", "usuut"}, {"mq_timedreceive", "usuut"},
    {"mq_notify", "ut"}, {"mq_getsetattr", "utt"},{"kexec_load", "uutu"},
    {"waitid", "dutdt"}, {"add_key", "sssu"}, {"request_key", "sssu"},
    {"keyctl", "duuuu"}, {"ioprio_set", "ddd"}, {"ioprio_get", "dd"},
    {"inotify_init", 0x0}, {"inotify_add_watch", "dsu"},
    {"inotify_rm_watch", "du"}, {"migrate_pages", "uupp"},
    {"openat", "dsdd"}, {"mkdirat", "dsd"}, {"mknodat","dsdu"},
    {"fchownat", "dsuud"}, {"futimesat", "dst"}, {"newfstatat", "dstd"},
    {"unlinkat", "dsd"}, {"renameat", "dsds"}, {"linkat", "dsdsd"},
    {"symlinkat", "sds"}, {"readlinkat", "dssd"}, {"fchmodat", "dsu"},
    {"faccessat", "dsu"}, {"pselect6", "dppptp"}, {"ppoll", "tutpu"},
    {"unshare", "u"}, {"set_robust_list", "tu"}, {"get_robust_list", "tu"},
    {"splice", "dpdpuu"}, {"tee", "dduu"}, {"sync_file_range", "dllu"},
    {"vmsplice", "dtuu"}, {"move_pages", "uupppd"}, {"utimensat", "dstd"},
    {"epoll_pwait", "dtddpu"}, {"signalfd", "dpu"}, {"timerfd_create", "dd"},
    {"eventfd", "u"}, {"fallocate", "ddll"}, {"timerfd_settime", "ddtt"},
    {"timerfd_gettime", "dt"}, {"accept4", "dtpd"}, {"signalfd4", "dtdd"},
    {"eventfd2", "ud"}, {"epoll_create1", "d"}, {"dup3", "uud"},
    {"pipe2", "pd"}, {"inotify_init1", "d"}, {"preadv", "utuuu"},
    {"pwritev", "utuuu"}, {"rt_tgsigqueueinfo", "uudp"},
    {"perf_event_open", "tuddu"}, {"recvmmsg", "dtuut"},
    {"fanotify_init", "uu"}, {"fanotify_mark", "ddldd"},
    {"prlimit64", "uutt"}, {"name_to_handle_at", "dstpd"},
    {"open_by_handle_at", "dstpd"}, {"clock_adjtime", "ut"}, {"syncfs", "d"},
    {"sendmmsg", "dtuu"}, {"setns", "dd"}, {"getcpu", "ppt"},
    {"process_vm_readv", "ututuu"}, {"process_vm_writev", "ututuu"},
    {"kcmp", "uuduu"}, {"finit_module", "dsd"}, {"sched_setattr", "utu"},
    {"sched_getattr", "utuu"}, {"renameat2", "dsdsu"}, {"seccomp", "uus"},
    {"getrandom", "suu"}, {"memfd_create", "su"},
    {"kexec_file_load", "ddusu"}, {"bpf", "dpu"}, {"execveat", "dsppd"},
    {"userfaultfd", "d"}, {"membarrier", "dd"}, {"mlock2", "uud"},
    {"copy_file_range", "dpdpuu"}, {"preadv2", "utuuud"},
    {"pwritev2", "utuuud"}, {0x0, 0x0}
};

static const syscall_t LIST_32BITS[] =
{
    {"reboot", "ddup"}, {"exit", "d"}, {"fork", 0x0}, {"read", "usu"},
    {"write", "usu"}, {"open", "sdd"}, {"close", "u"}, {"waitpid", "upd"},
    {"creat", "sd"}, {"link", "ss"}, {"unlink", "s"}, {"execve", "saa"},
    {"chdir", "s"}, {"time", "p"}, {"mknod", "suu"}, {"chmod", "st"},
    {"break", 0x0}, {"oldstat", 0x0}, {"lseek", "uuu"}, {"getpid", 0x0},
    {"mount", "sssup"}, {"unmount", "sssup"}, {"setuid", "u"},
    {"getuid", 0x0}, {"stime", "l"}, {"ptrace", "ddlu"},
    {"alarm", "d"}, {"oldstat", 0x0}, {"pause", 0x0},
    {"utime", "st"}, {"stty", 0x0}, {"gtty", 0x0},
    {"access", "sd"}, {"nice", "d"}, {"ftime", 0x0},
    {"sync", 0x0}, {"kill", "ud"}, {"rename", "ss"},
    {"mkdir", "sd"}, {"rmdir", "s"}, {"dup", "u"},
    {"pipe", "d"}, {"times", "t"}, {"prof", 0x0},
    {"brk", "u"}, {"setgid", "u"}, {"getgid", 0x0},
    {"signal", "p"}, {"geteuid", 0x0}, {"getegid", 0x0},
    {"acct", "s"}, {"umount2", "sd"}, {"lock", 0x0},
    {"ioctl", "uuu"}, {"fcntl", "uuu"}, {"mpx", 0x0},
    {"setpgid", "uu"}, {"ulimit", 0x0},
    {"oldolduname", 0x0}, {"umask", "d"}, {"chroot", "s"},
    {"ustat", "ut"}, {"dup2", "uu"}, {"getppid", 0x0},
    {"getpgrp", 0x0}, {"setsid", 0x0}, {"sigaction", 0x0},
    {"sgetmask", 0x0}, {"setreuid", "uu"}, {"setregid", "uu"},
    {"sigsuspend", "pu"}, {"sigpending", "uu"}, {"sethostname", "sd"},
    {"setrlimit", "ut"}, {"getrusage", "dt"}, {"gettimeofday", "tt"},
    {"settimeofday", "tt"}, {"getgroups", "dp"}, {"select", "dp"},
    {"symlink", "ss"}, {"oldlstat", 0}, {"readlink", "ssd"},
    {"uselib", "u"}, {"swapon", "sd"}, {"readdir", 0x0},
    {"mmap", "uuuuuu"}, {"munmap", "uu"}, {"truncate", "sl"},
    {"ftruncate", "ul"}, {"fchmod", "dsu"}, {"getpriority", "dd"},
    {"setpriority", "ddd"}, {"profil", 0x0}, {"statfs", "st"},
    {"fstatfs", "ut"}, {"ioperm", "uud"}, {"socketcall", 0x0},
    {"syslog", "dsd"}, {"setitimer", "ddt"}, {"getitimer", "dt"},
    {"stat", "st"}, {"fstat", "st"}, {"oldolduname", 0x0},
    {"iopl", "ut"}, {"vhangup", 0x0}, {"idle", 0x0},
    {"vm86old", 0x0}, {"wait4", "updt"}, {"swapoff", "s"},
    {"sysinfo", "t"}, {"ipc", 0x0}, {"fsync", "u"},
    {"sigreturn", "u"}, {"clone", "uupp"}, {"setdomainname", "sd"},
    {"uname", "t"}, {"modify_ldt", "dpu"}, {"adjtimex", "t"},
    {"mprotect", "uuu"}, {"sigprogmask", 0x0}, {"create_module", "uu"},
    {"init_module", "pus"}, {"delete_module", "su"}, {"get_kernel_syms", "t"},
    {"quotactl", "usup"}, {"getpgid", "u"}, {"fchdir", "u"},
    {"bdflush", 0x0}, {"sysfs", "duu"}, {"personality", "u"},
    {"afs_syscall", "uuuuu"}, {"setfsuid", "u"}, {"setfsgid", "u"},
    {"llseek", 0x0}, {"getdents", "utu"}, {"newselect", 0x0},
    {"flock", "uu"}, {"msync", "uud"}, {"readv", "utu"},
    {"writev", 0}, {"getsid", "u"},
    {"fdatasync", "u"}, {"sysctl", "t"}, {"mlock", "uu"},
    {"munlock", "uu"}, {"mlockall", "d"}, {"munlockall", 0x0},
    {"sched_setparam", "ut"}, {"sched_getparam", "ut"},
    {"sched_setscheduler", "ddt"}, {"sched_getscheduler", "u"},
    {"sched_yield", 0x0}, {"sched_get_priority_max", "d"},
    {"sched_get_priority_min", "d"}, {"sched_rr_get_interval", "ut"},
    {"nanosleep", "tt"}, {"mremap", "uuuuu"}, {"setresuid", "ppp"},
    {"getresuid", "ppp"}, {"vm86", 0x0}, {"query_module", "uuuuu"},
    {"poll", "tud"}, {"nfsservctl", "uuu"}, {"setresgid", "uuu"},
    {"getresgid", "ppp"}, {"prctl", "duuuu"}, {"rt_sigreturn", "u"},
    {"rt_sigaction", "dttu"}, {"rt_sigprocmask", 0x0}, {"rt_sigpending", "uu"},
    {"rt_sigtimedwait", "pptu"}, {"rt_sigqueueinfo", "udp"},
    {"rt_sigsuspend", "pu"}, {"pread64", "usuu"}, {"pwrite64", "utu"},
    {"chown", "suu"}, {"getcwd", "su"}, {"capget", "tt"},
    {"capset", "tt"}, {"sigaltstack", "pp"}, {"sendfile", "dd"},
    {"getpmsg", "uuuuu"}, {"putpmsg", "uuuuu"}, {"vfork", 0x0},
    {"ugetrlimit", 0x0}, {"mmap2", 0x0}, {"truncate64", 0x0},
    {"ftruncate64", 0x0}, {"stat64", 0x0}, {"lstat64", 0x0},
    {"fstat64", 0x0}, {"lchown32", 0x0}, {"getuid32", 0x0},
    {"getgid32", 0x0}, {"geteuid32", 0x0}, {"getegid32", 0x0},
    {"setreuid32", 0x0}, {"setregid32", 0x0}, {"getgroups32", 0x0},
    {"fchown32", 0x0}, {"setresuid32", 0x0}, {"getresuid32", 0x0},
    {"setresgid32", 0x0}, {"getresgid32", 0x0}, {"chown32", 0x0},
    {"setuid32", 0x0}, {"setgid32", 0x0}, {"setfsuid32", 0x0},
    {"setfsgid32", 0x0}, {"pivot_root", "ss"}, {"mincore", "uus"},
    {"madvise", "uud"}, {"getdents64", 0x0},
    {"fcntl64", 0x0}, {"gettid", 0x0}, {"readahead", "duu"},
    {"setxattr", "sspud"}, {"lsetxattr", "sspud"}, {"fsetxattr", "dspud"},
    {"getxattr", "sspd"}, {"lgetxattr", "sspu"}, {"fgetxattr", "dspu"},
    {"listxattr", "ssu"}, {"llistxattr", "ssu"}, {"flistxattr", "dsu"},
    {"removexattr", "ss"}, {"lremovexattr", "ss"}, {"fremovexattr", "ds"},
    {"tkill", "du"}, {"sendfile64", 0x0}, {"futex", "pdutpu"},
    {"sched_setaffinity", "uup"}, {"sched_getaffinity", "uup"},
    {"set_thread_area", "u"}, {"get_thread_area", "U"}, {"io_setup", "ut"},
    {"io_destroy", "u"}, {"io_getevents", "pllt"}, {"io_submit", "plt"},
    {"io_cancel", "ppt"}, {"fadvise64", "duud"}, {"exit_group", "d"},
    {"lookup_dcookie", "ull"}, {"epoll_create", "d"}, {"epoll_ctl", "dddt"},
    {"epoll_wait", "uuuu"}, {"remap_file_pages", "uuuuu"},
    {"set_tid_address", "p"},
    {"timer_create", "utp"}, {"timer_settime", "udtt"},
    {"timer_gettime", "ut"},
    {"timer_getoverrun", "u"}, {"timer_delete", "u"}, {"clock_settime", "ut"},
    {"clock_gettime", "ut"}, {"clock_getres", "ut"},
    {"clock_nanosleep", "udtt"},
    {"statfs64", 0x0}, {"fstatfs64", 0x0}, {"tgkill", "uud"},
    {"utimes", "st"}, {"fadvise64_64", 0x0}, {"vserver", "uuuuu"},
    {"mbind", "uuupuu"}, {"get_mempolicy", "ppuuuu"}, {"set_mempolicy", "puu"},
    {"mq_open", "sdut"}, {"mq_unlink", "s"}, {"mq_timedsend", "usuut"},
    {"mq_timedreceive", "usuut"}, {"mq_notify", "ut"},
    {"mq_getsetattr", "utt"},
    {"kexec_load", "uutu"}, {"waitid", "dutdt"}, {"add_key", "sssu"},
    {"request_key", "sssu"}, {"keyctl", "duuuu"}, {"ioprio_set", "ddd"},
    {"ioprio_get", "dd"}, {"inotify_init", 0x0}, {"inotify_add_watch", "dsu"},
    {"inotify_rm_watch", "du"}, {"migrate_pages", "uupp"}, {"openat", "dsdd"},
    {"mkdirat", "dsd"}, {"mknodat", "dsdu"}, {"fchownat", "dsuud"},
    {"futimesat", "dst"}, {"fstatat64", 0x0}, {"unlinkat", "dsd"},
    {"renameat", "dsds"}, {"linkat", "dsdsd"}, {"symlinkat", "sds"},
    {"chmodat", 0x0}, {"faccessat", "dsu"}, {"pselect6", "dppptp"},
    {"ppoll", "tutpu"}, {"unshare", "u"}, {"set_robust_list", "tu"},
    {"get_robust_list", "tu"}, {"splice", "dpdpuu"},
    {"sync_file_range", "dllu"}, {"tee", "duu"}, {"vmsplice", "dtuu"},
    {"move_pages", "uupppd"}, {"getcpu", "ppt"}, {"epoll_wait", 0x0},
    {"utimensat", "dstd"},
    {"signalfd", "dpu"}, {"timerfd_create", "dd"}, {"eventfd", "u"},
    {"fallocate", "ddll"}, {"timer_settime", "udtt"},
    {"timerfd_gettime", "dt"},
    {"signalfd4", "dtdd"}, {"eventfd2", "ud"}, {"epoll_create1", "d"},
    {"dup3", "uud"}, {"pipe2", "pd"}, {"inotify_init1", "d"},
    {"preadv", "utuuu"}, {"pwritev", "utuuu"}, {"rt_tgsigqueueinfo", "uudp"},
    {"perf_event_open", "tuddu"}, {"recvmsg", "dtu"}, {"fanotify_init", "uu"},
    {"fanotify_mark", "ddldd"}, {"prlimit64", "uutt"},
    {"name_to_handle_at", "dstpd"},
    {"open_by_handle_at", "dstpd"}, {"clock_adjtime", "ut"}, {"syncfs", "d"},
    {"sendmsg", "dtu"}, {"setns", "dd"}, {"process_vm_readv", "ututuu"},
    {"process_vm_writev", "ututuu"}, {"kcmp", "uuduu"},
    {"finit_module", "dsd"}, {"sched_setattr", "utu"},
    {"sched_getattr", "utuu"}, {"renameat2", "dsdsu"},
    {"seccomp", "uus"}, {"getrandom", "suu"}, {"memfd_create", "su"},
    {"bpf", "dpu"}, {"execveat", "dsppd"}, {"socket", "ddd"},
    {"socketpair", "dddp"}, {"bind", "dtd"}, {"connect", "dtd"},
    {"listen", "dd"}, {"accept4", "dtpd"}, {"getsockopt", "ddds"},
    {"setsockopt", "dddsd"}, {"getpeername", "dtd"}, {"sendto", "dpuutd"},
    {"sendmsg", "dtd"}, {"recvfrom", "dpuutd"}, {"recvmsg", "dtu"},
    {"shutdown", 0x0}, {"userfaultfd", "d"}, {"membarrier", "dd"},
    {"mlock2", "uud"}, {"copy_file_range", "dpduu"}, {"preadv2", "utuuud"},
    {"pwritev2", "utuuud"}, {"pkey_mprotect", 0x0}, {"pkey_alloc", 0x0},
    {"pkey_free", 0x0}, {"statx", 0x0}, {"arch_prctl", "tdu"},
    {"io_pgetevents", 0x0}, {"resq", 0x0}, {"semget", "udd"},
    {"shmctl", "ddt"}, {"shmat", "dsd"}, {"shmdt", "s"},
    {"msgget", "ud"}, {"msgsnd", "dtud"}, {"msgrcv", "dtuld"},
    {"msgctl", "ddt"}, {"clock_gettime64", "ut"}, {"clock_settime64", "ut"},
    {"clock_adjtime64", "ut"}, {"clock_getres_time64", "ut"},
    {"clock_nanosleep_time64", "udtt"}, {"timer_gettime64", "ut"},
    {"timer_settime64", "udtt"}, {"timerfd_gettime64", "dt"},
    {"timerfd_settime64", "ddtt"}, {"utimensat_time64", "dstd"},
    {"pselect6_time64", 0x0}, {"ppoll_time64", 0x0}, {"io_pgetevents", 0x0},
    {"recvmsg_time64", 0x0}, {"mq_timedsend_time64", 0x0},
    {"mq_timedreceive_time64", 0x0}, {"semtimedop_time64", 0x0},
    {"rt_sigtimedwait_time64", 0x0}, {"futex_time64", 0x0},
    {"sched_rr_get_interval_time64", 0x0}, {"io_uring_setup", 0x0},
    {"io_uring_enter", 0x0}, {"io_uring_register", 0x0}, {"open_tree", 0x0},
    {"move_mount", 0x0}, {"fsopen", 0x0}, {"fsconfig", 0x0},
    {"fsmount", 0x0}, {"fspick", 0x0}, {"pidfd_open", 0x0}, {"clone3", 0x0},
    {"close_range", 0x0}, {"openat2", 0x0}, {"pidfd_getfd", 0x0},
    {"faccessat2", 0x0}, {"process_madvise", 0x0}, {0x0, 0x0}
};

#endif /* SYSCALLS_H */
